queue_rules:
  - name: default
    conditions: []  # no extra conditions needed to get merged

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "check-success=SCA Test on CentOS/x64"
      - "check-success=UT Test on CentOS/x64"
      - "check-success=BVT Test on CentOS/x64"
      - "check-success=BVT RACE Test on CentOS/x64"
      - "check-success=Lint Docs"
    actions:
      queue:
        name: default
