# This is a basic workflow to help you get started with Actions

name: MatrixOne CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    types: [opened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-name:
    if: ${{ github.event.pull_request.base.repo.full_name == 'guguchecken/git_test' }}
    runs-on: ubuntu-latest
    
    name: SCA Test on CentOS/x64
    steps:
      - run: |
         echo ${{ github.event.pull_request.base.repo.full_name}}/${{ github.event.pull_request.base.ref }}/${{ github.workflow }}

