# This is a basic workflow to help you get started with Actions

name: Issue Time CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: guguducken/issue-time-action@main
        with: 
          token_action: ${{ secrets.ACTION_TOKEN }}
          warning_time: "24 72 168"
          uri_warn: ${{ secrets.MATRIXONE_HOOK }}
          label_check: "severity/s-1,severity/s0,severity/s1"
          repos: "matrixorigin/matrixone,matrixorigin/MO-Cloud"
          corresponding: "{\"fengttt\":\"TianFeng\",\"yingfeng\":\"yingfeng.zhang\",\"jinhai-CN\":\"hai.jin\",\"XuPeng-SH\":\"xupeng\",\"volgariver6\":\"bol\",\"nttstar\":\"jiaguo@matrixorigin.cn\",\"matrix-meow\":\"matrixorigin\",\"jiangxinmeng1\":\"JiangXinMeng\",\"aptend\":\"HanFeng\",\"triump2020\":\"Fi\",\"LeftHandCold\":\"ShenJiangWei\",\"cnutshell\":\"CuiGuoKe\",\"daviszhen\":\"PengZhen\",\"mooleetzi\":\"mooleetzi\",\"iamlinjunhong\":\"LinJunHong\",\"bbbearxyz\":\"bbbearxyz\",\"ouyuanning\":\"OuYuanNing\",\"jianwan0214\":\"WangXiaoJuan\",\"qingxinhome\":\"WuXiliang\",\"nnsgmsone\":\"nnsgmsone\",\"m-schen\":\"ChenMingSong\",\"jensenojs\":\"1\",\"JackTan25\":\"TanBoYu\",\"dongdongyang33\":\"wuqinxuan\",\"aunjgr\":\"longran\",\"zhangxu19830126\":\"zx\",\"reusee\":\"YueSheng\",\"w-zr\":\"WeiZiRan\",\"sukki37\":\"shuqi.qin\",\"guguducken\":\"JiejieJia\",\"jqh9804\":\"jqh9804\",\"wanglei4687\":\"WangLeilei\",\"aylei\":\"Aylei\",\"xzxiong\":\"jacksonxie\",\"xuoutput\":\"hengxu\",\"DanielZhangQD\":\"DanielZhang\",\"aressu1985\":\"SuDong\",\"heni02\":\"HENI\",\"tianyahui-python\":\"eric\",\"goodMan-code\":\"matrix_zxg\",\"florashi181\":\"florashi\",\"dengn\":\"DengNan\",\"LiSong0214\":\"Song\",\"domingozhang\":\"ZhangXiao\",\"lacriosaprinz\":\"Prinz\",\"badboynt1\":\"nitao\",\"YANGGMM\":\"Andy\"}"
          mentions: "JiejieJia"
