# This is a basic workflow to help you get started with Actions

name: Issue Time CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: guguducken/issue-time-action@main
        with: 
          token_action: ${{ secrets.ACTION_TOKEN }}
          error_time: "100 0 0 0 0"
          warning_time: "50 0 0 0 0"
          uri_warn: ${{ secrets.MATRIXONE_HOOK }}
          uri_error: ${{ secrets.MATRIXONE_HOOK }}
          label_check: "kind/bug"
