# This is a basic workflow to help you get started with Actions

name: auto add issue to project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  issues:
    types: 
      - opened
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  auto-to-project:
    runs-on: ubuntu-latest
    
    steps:
      - name: Add To GitHub Projects Beta
        uses: actions/add-to-project@v0.1.0
        with:
          project-url: ${{ secrets.PROJECT_NAME }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: kind/bug,kind/doc
          label-operator: OR
